### ISSUE TITLE
Scrolling along X axis still allowed, fixed with overflow: hidden

### ISSUE THREAD

**Issue by xvjg** [uicardiodev/hugo-uilite#15]
On Safari (Mac), I can scroll left and right. Here is an image:

![scrolling on mac](https://i.imgur.com/U6ZNRkV.png)

Also there's a small gutter to the right on Samsung Browser.

I fixed it on my personal site by setting:

```css
body {
    overflow: hidden;
}
```
